name: dart_conf_flutter
description: A conference app for DartConf 2018.

dependencies:
  cloud_firestore: ^0.1.0
  cupertino_icons: ^0.1.0
  flutter:
    sdk: flutter
  http: ^0.11.0
  intl: ^0.15.0
  url_launcher: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/dartconf.png
    - assets/google_la_map.png
    - assets/app.token.txt
